# Generated by Django 4.1.7 on 2023-03-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("button_text", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="media/banner/%Y/")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
