# Generated by Django 4.2 on 2023-04-12 07:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coder",
            name="category",
            field=models.CharField(
                choices=[
                    ("full_stack", "full stack"),
                    ("fornt_end", "front end"),
                    ("back_end", "back end"),
                    ("web_development", "web development"),
                    ("data_analysis", "data analysis"),
                    ("dev_ops", "dev ops"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="coder",
            name="type",
            field=models.CharField(
                choices=[
                    ("company", "company"),
                    ("individual", "individual"),
                    ("team", "team"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="coder",
            name="work_history",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
